apiVersion: v1
kind: ConfigMap
metadata:
  name: fhir-server-config
data:
  extension-search-parameters.json: >
    {
      "resourceType": "Bundle",
      "id": "searchParams",
      "meta": {
        "lastUpdated": "2018-12-27T22:37:54.724+11:00"
      },
      "type": "collection",
      "entry": []
    }
  fhir-server-config.json: >
    {
      "__comment": "config for the externally-visible fhir deployment",
      "fhirServer": {
        "core": {
          "tenantIdHeaderName": "X-FHIR-TENANT-ID",
          "datastoreIdHeaderName": "X-FHIR-DSID",
          "checkReferenceTypes": true,
          "conditionalDeleteMaxNumber": 1,
          "defaultPrettyPrint": true,
          "originalRequestUriHeaderName": "X-FHIR-FORWARDED-URL",
          "serverRegistryResourceProviderEnabled": false
        },
        "resources": {
          "open": true,
          "Resource": {
            "interactions": ["read", "vread", "history", "search"]
          }
        },
        "security": {
          "cors": true,
          "basic": {
            "enabled": true
          },
          "certificates": {
            "enabled": true,
            "authFilter": {
              "enabled": false
            }
          },
          "oauth": {
            "enabled": false,
            "regUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/registration",
            "authUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/authorize",
            "tokenUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/token",
            "smart": {
              "enabled": false,
              "scopes": ["openid", "profile", "fhirUser", "launch/patient", "offline_access",
                "patient/*.read",
                "patient/AllergyIntolerance.read",
                "patient/CarePlan.read",
                "patient/CareTeam.read",
                "patient/Condition.read",
                "patient/Device.read",
                "patient/DiagnosticReport.read",
                "patient/DocumentReference.read",
                "patient/Encounter.read",
                "patient/ExplanationOfBenefit.read",
                "patient/Goal.read",
                "patient/Immunization.read",
                "patient/Location.read",
                "patient/Medication.read",
                "patient/MedicationRequest.read",
                "patient/Observation.read",
                "patient/Organization.read",
                "patient/Patient.read",
                "patient/Practitioner.read",
                "patient/PractitionerRole.read",
                "patient/Procedure.read",
                "patient/Provenance.read",
                "patient/RelatedPerson.read"
              ],
              "capabilities": [
                "sso-openid-connect",
                "launch-standalone",
                "client-public",
                "client-confidential-symmetric",
                "permission-offline",
                "context-standalone-patient",
                "permission-patient"
              ]
            }
          }
        },
        "audit": {
          "serviceClassName": "com.ibm.fhir.audit.logging.impl.DisabledAuditLogService",
          "serviceProperties": {
          }
        },
        "persistence": {
          "factoryClassname": "com.ibm.fhir.persistence.jdbc.FHIRPersistenceJDBCFactory",
          "common": {
            "__comment": "Configuration properties common to all persistence layer implementations",
            "updateCreateEnabled": true
          },
          "datasources": {
            "default": {
                "type": "postgresql",
                "connectionProperties": {
                    "serverName": "${FHIR_DB_HOSTNAME}",
                    "portNumber": ${FHIR_DB_PORT},
                    "ssl": true,
                    "sslmode": "verify-full",
                    "sslrootcert": "/opt/ol/wlp/usr/servers/fhir-server/resources/security/postgres.cert",
                    "databaseName": "${FHIR_DB_NAME}",
                    "user": "${FHIR_DB_USERNAME}",
                    "password": "${FHIR_DB_PASSWORD}",
                    "currentSchema": "${FHIR_DB_SCHEMA}"
                }
            }
          },
          "jdbc": {
            "dataSourceJndiName": "jdbc/fhirProxyDataSource",
            "enableCodeSystemsCache": true,
            "enableParameterNamesCache": true,
            "enableResourceTypesCache": true
          }
        },
        "bulkdata": {
          "bulkDataBatchJobIdEncryptionKey": "{xor}Lz4sLCgwLTs=",
          "applicationName": "fhir-bulkimportexport-webapp",
          "moduleName": "fhir-bulkimportexport.war",
          "jobParameters": {
            "cos.bucket.name": "fhir-export-changeme",
            "cos.location": "us",
            "cos.endpointurl": "https://s3.private.us-south.cloud-object-storage.appdomain.cloud",
            "fhir.tenant": "default",
            "cos.credential.ibm": "Y",
            "cos.api.key": "change-password",
            "cos.srvinst.id": "crn:v1:bluemix:public:cloud-object-storage:global:a/changeme::"
          },
          "implementation_type": "cos",
          "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances",
          "batch-user": "fhiruser",
          "batch-user-password": "change-password",
          "batch-truststore" : "resources/security/fhirTrustStore.p12",
          "useFhirServerTrustStore": "Y",
          "batch-truststore-password" : "change-password",
          "validBaseUrls": []
        }
      }
    }
