{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  annotations:
    ingress.bluemix.net/ssl-services: {{ .Values.ingress.sslServices }}
    ingress.bluemix.net/redirect-to-https: "True"
    ingress.bluemix.net/hsts: enabled=true maxAge=86400
    ingress.bluemix.net/location-snippets: |
      serviceName=fhir
      proxy_set_header X-FHIR-FORWARDED-URL https://$host$request_uri;
      limit_except GET HEAD {
          deny all;
      }
      <EOS>
      serviceName=fhir-post
      proxy_set_header X-FHIR-FORWARDED-URL https://$host$request_uri;
      limit_except POST {
          deny all;
      }
      <EOS>
    ingress.bluemix.net/location-modifier: modifier='~' serviceName=fhir-post
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: fhir
            servicePort: 9443
        - path: /fhir-server/api/v4/[\\w]+/_search
          backend:
            serviceName: fhir-post
            servicePort: 9443
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
