apiVersion: v1
kind: Secret
metadata:
  name: object-storage-secret
type: Opaque
data:
  cos.location: {{ .Values.objectStorage.location | b64enc }}
  cos.endpoint.url: {{ .Values.objectStorage.endpointUrl | b64enc }}
  cos.api.key: {{ .Values.objectStorage.apiKey | b64enc }}
  cos.srvinstid: {{ .Values.objectStorage.serviceInstanceId | b64enc }}
