apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
spec:
  selector:
    app: {{ template "name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.internalPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-post
spec:
  selector:
    app: {{ template "name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.internalPort }}
