# Jekyll Configuration for Static Pages

title: IBM FHIR Server
description: >- 
  The IBM FHIR Server is a modular Java implementation of version 4 
  of the <a href="https://www.hl7.org/fhir/r4/http.html">HL7 FHIR specification</a> with 
  a focus on performance and configurability.
baseurl: ""
url: "https://ibm.github.io/fhir" 
