name: Integration - Audit

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'demo/**'
      - '.github/workflows/site.yml'
      - '.github/workflows/release.yml'

jobs:
  e2e-audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ '11' ]
        audit: [ 'kafka' ]
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.3
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Setup prerequisites
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/audit/bin/setup-prerequisites.sh ${{matrix.audit}}
    - name: Server Integration Tests - Audit
      env:
        WORKSPACE: ${{ github.workspace }}
      # fail-fast behavior is set when `shell: bash` is explicitly specified. It is not applied by default.
      shell: bash
      run: |
        bash build/audit/bin/pre-integration-test.sh ${{matrix.audit}}
        bash build/audit/bin/integration-test.sh ${{matrix.audit}}
        bash build/audit/bin/post-integration-test.sh ${{matrix.audit}}
    - name: Gather error logs
      if: failure()
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/audit/bin/gather-logs.sh ${{matrix.audit}}
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: integration-test-results-${{ matrix.audit }}-${{ matrix.java }}
        path: build/audit/integration-test-results

concurrency:
  group: audit-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true