name: CI

on:
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:
  build-tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11.0.1' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build tools
      run: mvn -B install --file fhir-tools/pom.xml --no-transfer-progress
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent without tests
      run: mvn -B install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress
    - name: Build sample generator
      run: mvn -B package --file fhir-examples-generator/pom.xml --no-transfer-progress
    - name: Build benchmark
      run: mvn -B package --file fhir-benchmark/pom.xml --no-transfer-progress
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11.0.1' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent with tests
      run: mvn -B -T2C package --file fhir-parent/pom.xml --no-transfer-progress
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11.0.1' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent without tests
      run: mvn -B install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress
    - name: Server Integration Tests
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/pre-integration-test.sh
        mvn -B test -DskipTests=false -f fhir-server-test/pom.xml -DskipWebSocketTest=true --no-transfer-progress
        build/post-integration-test.sh
    - name: Gather error logs
      if: failure()
      run: |
        it_results=SIT/integration-test-results
        rm -fr ${it_results} 2>/dev/null
        mkdir -p ${it_results}/server-logs
        mkdir -p ${it_results}/fhir-server-test
        echo "Gathering post-test server logs..."
        cp -pr SIT/wlp/usr/servers/fhir-server/logs ${it_results}/server-logs
        echo "Gathering integration test output"
        cp -pr ${GITHUB_WORKSPACE}/fhir-server-test/target/surefire-reports/* ${it_results}/fhir-server-test
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: integration-test-results
        path: SIT/integration-test-results
