name: Integration

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '.github/site.yml'

jobs:
  build-tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build tools
      run: mvn -B install --file fhir-tools/pom.xml
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml
    - name: Build parent without tests
      run: mvn -B install --file fhir-parent/pom.xml -DskipTests
    - name: Build sample generator
      run: mvn -B package --file fhir-examples-generator/pom.xml
    - name: Build benchmark
      run: mvn -B package --file fhir-benchmark/pom.xml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent with tests
      env:
        BASE: origin/${{ github['base_ref'] }}
      run: |
        model_paths=(
          fhir-model
          fhir-examples
        )
        validation_paths=(
          fhir-validation
          fhir-path/src/main
          fhir-model/src/main
          fhir-examples
        )
        search_paths=(
          fhir-search
          fhir-examples
        )
        jdbc_paths=(
          fhir-persistence-jdbc
          fhir-search/src/main
          fhir-persistence/src/main
          fhir-persistence-schema/src/main
          fhir-examples
        )
        declare -a PROFILES_ARR

        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${model_paths[@]})" ]; then
          echo "Changes affect fhir-model, running ALL"
          PROFILES_ARR+=(model-all-tests)
        else
          echo "No changes affect fhir-model, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${validation_paths[@]})" ]; then
          echo "Changes affect fhir-validation, running ALL"
          PROFILES_ARR+=(validation-all-tests)
        else
          echo "No changes affect fhir-validation, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${search_paths[@]})" ]; then
          echo "Changes affect fhir-search, running ALL"
          PROFILES_ARR+=(search-all-tests)
        else
          echo "No changes affect fhir-search, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${jdbc_paths[@]})" ]; then
          echo "Changes affect fhir-persistence-jdbc, running ALL"
          PROFILES_ARR+=(jdbc-all-tests)
        else
          echo "No changes affect fhir-persistence-jdbc, running MINIMAL"
        fi

        if [ ${#PROFILES[@]} -eq 0 ]; then
          # Convert the PROFILES_ARR array to a comma-delimited string
          PROFILES=$(IFS=, ; echo "${PROFILES_ARR[*]}")
          echo "Using profiles ${PROFILES}"
          mvn -B -T2C package --file fhir-parent/pom.xml -P "${PROFILES}" --no-transfer-progress
        else
          mvn -B -T2C package --file fhir-parent/pom.xml --no-transfer-progress
        fi
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent without tests
      # As the e2e tests are the fastest, opting to put javadoc:javadoc in fhir-parent
      # The profile avoids UML diagram creation
      run: |
        JAVADOC_GOAL=""
        if [ "${{ matrix.java }}" != "openjdk8" ]
        then 
          export JAVA_HOME=/opt/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-${{ matrix.java }}-hotspot-normal-latest/x64/
          JAVADOC_GOAL=" -Pvalidate-javadoc javadoc:javadoc "
        fi
        mvn -B ${JAVADOC_GOAL} install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress
    - name: Server Integration Tests
      env:
        # debian-based linux uses C.UTF-8 by default and Derby doesn't like that
        LC_ALL: en_US.UTF-8
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/pre-integration-test.sh
        env
        mvn -B test -DskipTests=false -f fhir-server-test/pom.xml -DskipWebSocketTest=true --no-transfer-progress
        build/post-integration-test.sh
    - name: Gather error logs
      if: failure()
      run: |
        it_results=SIT/integration-test-results
        rm -fr ${it_results} 2>/dev/null
        mkdir -p ${it_results}/server-logs
        mkdir -p ${it_results}/fhir-server-test
        echo "Gathering post-test server logs..."
        cp -pr SIT/wlp/usr/servers/fhir-server/logs ${it_results}/server-logs
        echo "Gathering integration test output"
        cp -pr ${GITHUB_WORKSPACE}/fhir-server-test/target/surefire-reports/* ${it_results}/fhir-server-test
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: integration-test-results-${{ matrix.java }}
        path: SIT/integration-test-results
  e2e-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      shell: powershell
      run: mvnw -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent without tests
      shell: powershell
      run: mvnw -B install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress
    - name: Server Integration Tests
      shell: powershell
      run: |
        $WORKSPACE=%GITHUB_WORKSPACE%
        & build/pre-integration-test.ps1
        mvnw -B test -DskipTests=false -f fhir-server-test/pom.xml -DskipWebSocketTest=true --no-transfer-progress
        & build/post-integration-test.ps1
    - name: Gather error logs
      shell: powershell
      if: failure()
      run: |
        $it_results=SIT/integration-test-results
        Remove-Item –path $it_results –recurse -force
        New-Item -Name $it_results/server-logs -ItemType directory -force
        New-Item -Name $it_results/fhir-server-test -ItemType directory -force
        Write-Output "Gathering post-test server logs..."
        Copy-Item SIT/wlp/usr/servers/fhir-server/logs -Destination $it_results/server-logs -Recurse
        Write-Output "Gathering integration test output"
        Copy-Item "$Env:GITHUB_WORKSPACE/fhir-server-test/target/surefire-reports/*" -Destination $it_results/fhir-server-test -Recurse
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: integration-test-results-windows-${{ matrix.java }}
        path: SIT/integration-test-results
