name: Integration - Persistence

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - '.github/workflows/site.yml'
      - '.github/workflows/release.yml'

jobs:
  e2e-persistence:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ '11' ]
        persistence: [ 'postgres' ]
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.3
    - name: Set up java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Setup prerequisites
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/persistence/bin/setup-prerequisites.sh ${{matrix.persistence}}
    - name: Server Integration Tests - Additional Persistence Layers
      env:
        WORKSPACE: ${{ github.workspace }}
      run: |
        bash build/persistence/bin/pre-integration-test.sh ${{matrix.persistence}}
        bash build/persistence/bin/integration-test.sh ${{matrix.persistence}}
        bash build/persistence/bin/post-integration-test.sh ${{matrix.persistence}}
    - name: Gather error logs
      if: failure()
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/persistence/bin/gather-logs.sh ${{matrix.persistence}}
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: integration-test-results-${{ matrix.persistence }}-${{ matrix.java }}
        path: build/persistence/integration-test-results

concurrency:
  group: persistence-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true